'use client';
import React,{useEffect,useMemo,useState}from'react';
import{createClient}from'@/lib/supabase/client';
import{Button}from'@/components/ui/Button';
import{Printer,Tags,FileDown}from'lucide-react';
type Lot={id:string;code:string;beer_style:string;status:string};type Bottle={serial_code:string;unit_number:number;status:string};
export default function LabelsPage(){const supabase=useMemo(()=>createClient(),[]);const[lots,setLots]=useState<Lot[]>([]);const[lotId,setLotId]=useState('');const[units,setUnits]=useState<Bottle[]>([]);const[start,setStart]=useState(1);const[count,setCount]=useState(24);const[error,setError]=useState<string|null>(null);
useEffect(()=>{void(async()=>{const{data,error}=await supabase.from('investment_production_lots').select('id,code,beer_style,status').order('created_at',{ascending:false});if(error){setError(error.message);return}const r=(data??[])as Lot[];setLots(r);setLotId(r[0]?.id??'')})()},[]);
useEffect(()=>{if(!lotId){setUnits([]);return}void(async()=>{const{data,error}=await supabase.from('investment_bottle_units').select('serial_code,unit_number,status').eq('lot_id',lotId).order('unit_number');if(error){setError(error.message);return}setUnits((data??[])as Bottle[])})()},[lotId]);
const lot=lots.find(l=>l.id===lotId);const selected=units.filter(u=>u.unit_number>=start).slice(0,Math.max(1,Math.min(count,240)));const trace=(s:string)=>`${window.location.origin}/beer/${encodeURIComponent(s)}`;
const csv=()=>{if(!lot)return;const rows=['serial_code,unit_number,status,trace_url',...selected.map(u=>`${u.serial_code},${u.unit_number},${u.status},${trace(u.serial_code)}`)];const blob=new Blob([rows.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${lot.code}-labels.csv`;a.click();URL.revokeObjectURL(a.href)};
return <div className="space-y-6"><header className="rounded-[28px] border border-white/10 p-6 sm:p-8 bg-white/[.02]"><p className="text-[9px] uppercase tracking-[.28em] text-accent mb-3">CTG One · Traceability</p><h1 className="text-3xl sm:text-5xl font-outfit font-semibold">QR & Label Factory</h1><p className="text-sm text-text-muted mt-3 max-w-3xl">Prepara manifiestos imprimibles por serial. Cada etiqueta apunta a la trazabilidad pública de la botella; no representa propiedad económica sobre la unidad física.</p></header>{error&&<div className="rounded-xl border border-red-500/30 bg-red-500/[.06] p-3 text-sm text-red-300">{error}</div>}<section className="grid lg:grid-cols-4 gap-3 rounded-2xl border border-white/10 p-5 bg-white/[.02]"><select className="lg:col-span-2 rounded-xl px-3 py-3 bg-black/30 border border-white/10 text-white" value={lotId} onChange={e=>setLotId(e.target.value)}>{lots.map(l=><option key={l.id} value={l.id}>{l.code} · {l.beer_style}</option>)}</select><input type="number" min={1} value={start} onChange={e=>setStart(Number(e.target.value)||1)} className="rounded-xl px-3 py-3 bg-black/30 border border-white/10 text-white" placeholder="Desde unidad"/><input type="number" min={1} max={240} value={count} onChange={e=>setCount(Number(e.target.value)||24)} className="rounded-xl px-3 py-3 bg-black/30 border border-white/10 text-white" placeholder="Cantidad"/></section><div className="flex flex-wrap gap-3"><Button onClick={()=>window.print()} variant="primary" size="sm"><Printer size={15}/> Imprimir etiquetas</Button><Button onClick={csv} variant="secondary" size="sm"><FileDown size={15}/> Exportar manifiesto CSV</Button><span className="text-xs text-text-dim self-center">{selected.length} de {units.length} seriales</span></div><section className="label-sheet grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-3">{selected.map(u=><article key={u.serial_code} className="label-card rounded-xl border border-white/15 p-4 bg-white text-black break-inside-avoid"><div className="flex items-center gap-2"><Tags size={15}/><strong className="text-xs">CTG CRAFT BEER</strong></div><p className="text-[10px] mt-2">{lot?.beer_style}</p><p className="font-mono text-[11px] font-bold mt-1">{u.serial_code}</p><div className="mt-3 border border-black/20 p-2 text-[8px] font-mono break-all">{trace(u.serial_code)}</div><p className="text-[8px] mt-2">Escanea/abre la URL para consultar trazabilidad. Unidad física sin asignación de propiedad económica.</p></article>)}</section><style jsx global>{`@media print{nav,button,header,.label-sheet~*{display:none!important}body{background:#fff!important}.label-sheet{display:grid!important;grid-template-columns:repeat(3,1fr)!important;gap:8mm!important}.label-card{border:1px solid #111!important;break-inside:avoid!important}}`}</style></div>}
