'use client';

import React,{useEffect,useMemo,useState}from'react';
import{createClient}from'@/lib/supabase/client';
import{Button}from'@/components/ui/Button';
import{formatCents}from'@/lib/format';
import{BadgeCheck,PackageCheck,ReceiptText,RotateCcw,ShieldCheck}from'lucide-react';

type Sale={id:string;lot_id:string;sale_reference:string|null;gross_revenue_cents:number;tax_recognized_cents:number;sold_at:string;location:string|null};
type SaleItem={id:string;sale_id:string;bottle_unit_id:string;serial_code:string;line_total_cents:number};
type CreditNote={id:string;sale_id:string;credit_reference:string|null;reason_code:string;gross_credit_cents:number;tax_credit_cents:number;confirmed_at:string;return_location_id:string};
type CreditItem={sale_item_id:string;credit_note_id:string;serial_code:string;gross_credit_cents:number;tax_credit_cents:number};
type Location={id:string;code:string;name:string;location_type:string};
type Lot={id:string;code:string;beer_style:string};
type Reconciliation={sale_id:string;sold_units:number;returned_units:number;credit_note_count:number;gross_credit_cents:number;net_revenue_cents:number;tax_credit_cents:number;net_tax_cents:number;physical_return_mismatches:number;financial_reversal_mismatches:number;return_state:string;is_reconciled:boolean};

const REASONS=[['CUSTOMER_RETURN','Devolución del cliente'],['QUALITY_ISSUE','Incidencia de calidad'],['DAMAGED_PRODUCT','Producto dañado'],['WRONG_PRODUCT','Producto incorrecto'],['OTHER','Otro']] as const;

function browserIdempotencyKey(){if(typeof crypto!=='undefined'&&typeof crypto.randomUUID==='function')return crypto.randomUUID();return`credit-${Date.now()}-${Math.random().toString(36).slice(2,12)}`}

export default function ReturnsPage(){
  const supabase=useMemo(()=>createClient(),[]);
  const[sales,setSales]=useState<Sale[]>([]);const[items,setItems]=useState<SaleItem[]>([]);const[notes,setNotes]=useState<CreditNote[]>([]);const[creditItems,setCreditItems]=useState<CreditItem[]>([]);const[locations,setLocations]=useState<Location[]>([]);const[lots,setLots]=useState<Lot[]>([]);const[reconciliation,setReconciliation]=useState<Reconciliation[]>([]);
  const[saleId,setSaleId]=useState('');const[selected,setSelected]=useState<string[]>([]);const[returnLocation,setReturnLocation]=useState('');const[reason,setReason]=useState('CUSTOMER_RETURN');const[reference,setReference]=useState('');const[notesText,setNotesText]=useState('');const[idempotencyKey,setIdempotencyKey]=useState('');const[canManage,setCanManage]=useState(false);const[busy,setBusy]=useState(false);const[message,setMessage]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);

  const load=async()=>{setError(null);const[{data:s,error:se},{data:i,error:ie},{data:n,error:ne},{data:ci,error:cie},{data:l,error:le},{data:lotsData,error:loe},{data:r,error:re},{data:p,error:pe}]=await Promise.all([
    supabase.from('investment_sales').select('id,lot_id,sale_reference,gross_revenue_cents,tax_recognized_cents,sold_at,location').eq('status','CONFIRMED').order('sold_at',{ascending:false}),
    supabase.from('investment_sale_items').select('id,sale_id,bottle_unit_id,serial_code,line_total_cents'),
    supabase.from('investment_sales_credit_notes').select('id,sale_id,credit_reference,reason_code,gross_credit_cents,tax_credit_cents,confirmed_at,return_location_id').order('confirmed_at',{ascending:false}),
    supabase.from('investment_sales_credit_note_items').select('sale_item_id,credit_note_id,serial_code,gross_credit_cents,tax_credit_cents'),
    supabase.from('investment_inventory_locations').select('id,code,name,location_type').eq('active',true).in('location_type',['WAREHOUSE','SALES_POINT','PARTNER','QUARANTINE','OTHER']).order('name'),
    supabase.from('investment_production_lots').select('id,code,beer_style'),
    supabase.rpc('get_sales_return_reconciliation',{p_sale_id:null}),
    supabase.rpc('has_investment_permission',{p_permission:'sales.manage'}),
  ]);
  const firstError=se||ie||ne||cie||le||loe||re||pe;if(firstError){setError(firstError.message);return;}
  const saleRows=(s??[])as Sale[];setSales(saleRows);setItems((i??[])as SaleItem[]);setNotes((n??[])as CreditNote[]);setCreditItems((ci??[])as CreditItem[]);const locRows=(l??[])as Location[];setLocations(locRows);setLots((lotsData??[])as Lot[]);setReconciliation((r??[])as Reconciliation[]);setCanManage(Boolean(p));setSaleId(prev=>prev||saleRows[0]?.id||'');setReturnLocation(prev=>prev||locRows[0]?.code||'');};
  useEffect(()=>{void load();},[]);
  useEffect(()=>{setSelected([]);setReference('');setNotesText('');setIdempotencyKey('');},[saleId]);

  const sale=sales.find(row=>row.id===saleId);const lot=lots.find(row=>row.id===sale?.lot_id);const saleItems=items.filter(row=>row.sale_id===saleId).sort((a,b)=>a.serial_code.localeCompare(b.serial_code));const creditedIds=new Set(creditItems.map(row=>row.sale_item_id));const available=saleItems.filter(row=>!creditedIds.has(row.id));const selectedItems=saleItems.filter(row=>selected.includes(row.serial_code));const grossCredit=selectedItems.reduce((sum,row)=>sum+Number(row.line_total_cents||0),0);
  const taxShares=useMemo(()=>{const map=new Map<string,number>();if(!sale||saleItems.length===0)return map;const base=Math.floor(Number(sale.tax_recognized_cents)/saleItems.length);const remainder=Number(sale.tax_recognized_cents)%saleItems.length;saleItems.forEach((row,index)=>map.set(row.id,base+(index<remainder?1:0)));return map;},[saleId,sale?.tax_recognized_cents,items]);
  const taxCredit=selectedItems.reduce((sum,row)=>sum+(taxShares.get(row.id)??0),0);const rec=reconciliation.find(row=>row.sale_id===saleId);const saleNotes=notes.filter(row=>row.sale_id===saleId);

  const toggle=(serial:string)=>setSelected(current=>current.includes(serial)?current.filter(value=>value!==serial):[...current,serial]);
  const submit=async()=>{if(!sale||!selected.length||!returnLocation||!canManage)return;setBusy(true);setError(null);setMessage(null);const key=idempotencyKey||browserIdempotencyKey();if(!idempotencyKey)setIdempotencyKey(key);const{data,error:rpcError}=await supabase.rpc('record_sale_return_credit_note',{p_sale_id:sale.id,p_serial_codes:selected,p_return_location:returnLocation,p_reason_code:reason,p_idempotency_key:key,p_credit_reference:reference||null,p_notes:notesText||null});if(rpcError)setError(rpcError.message);else{const row=Array.isArray(data)?data[0]:data;setMessage(`Nota crédito registrada · ${row?.returned_count??selected.length} unidad(es) · ${formatCents(Number(row?.gross_credit_cents??grossCredit))}.`);setSelected([]);setReference('');setNotesText('');setIdempotencyKey('');await load();}setBusy(false);};

  return <div className="space-y-6">
    <header className="rounded-[28px] border border-white/10 p-6 sm:p-8" style={{background:'linear-gradient(135deg,rgba(18,18,18,.98),rgba(7,7,7,.95))'}}><p className="text-[9px] uppercase tracking-[.28em] text-accent mb-3">Sales OS · Reverse Flow</p><h1 className="text-3xl sm:text-5xl font-outfit font-semibold">Devoluciones & Credit Notes</h1><p className="text-sm text-text-muted mt-3 max-w-3xl">La venta original permanece inmutable. Cada devolución vincula seriales vendidos, movimiento físico desde custodia del cliente, reversión de ingreso/impuesto y evidencia auditable.</p></header>
    {(message||error)&&<div className="rounded-xl border px-4 py-3 text-sm" style={{borderColor:error?'rgba(239,68,68,.3)':'rgba(34,197,94,.25)',background:error?'rgba(239,68,68,.06)':'rgba(34,197,94,.05)',color:error?'#fca5a5':'#86efac'}}>{error??message}</div>}
    <section className="rounded-2xl border border-white/10 p-5 sm:p-6 bg-white/[.02]"><label className="block text-[9px] uppercase tracking-[.13em] text-text-dim mb-2">Venta confirmada</label><select className="w-full rounded-xl px-3 py-3 bg-white/[.025] border border-white/10 text-white" value={saleId} onChange={e=>setSaleId(e.target.value)}><option value="">Selecciona una venta</option>{sales.map(row=>{const l=lots.find(x=>x.id===row.lot_id);return <option key={row.id} value={row.id}>{l?.code??row.lot_id.slice(0,8)} · {row.sale_reference||row.id.slice(0,8)} · {formatCents(row.gross_revenue_cents)}</option>})}</select></section>
    {sale&&<><section className="grid grid-cols-2 xl:grid-cols-5 gap-3"><Metric icon={<ReceiptText/>} label="Venta original" value={formatCents(sale.gross_revenue_cents)}/><Metric icon={<RotateCcw/>} label="Crédito acumulado" value={formatCents(rec?.gross_credit_cents??0)}/><Metric icon={<PackageCheck/>} label="Unidades retornadas" value={`${rec?.returned_units??0}/${rec?.sold_units??saleItems.length}`}/><Metric icon={<ShieldCheck/>} label="Ingreso neto" value={formatCents(rec?.net_revenue_cents??sale.gross_revenue_cents)} accent/><Metric icon={<BadgeCheck/>} label="Reconciliación" value={rec?.is_reconciled?'OK':rec?'REVISAR':'—'} /></section>
    <section className="grid grid-cols-1 xl:grid-cols-[1.15fr_.85fr] gap-5"><div className="rounded-2xl border border-white/10 p-5 sm:p-6 bg-white/[.02]"><div className="flex items-center justify-between gap-3 mb-5"><div><p className="text-[9px] uppercase tracking-[.18em] text-text-dim">SERIAL RETURN SET</p><h2 className="text-xl font-outfit font-semibold mt-1">{lot?.code??'Lote'} · seleccionar unidades</h2></div><span className="text-[10px] text-text-dim">Disponibles: {available.length}</span></div>{available.length===0?<p className="text-sm text-text-muted">No quedan unidades elegibles para devolución en esta venta.</p>:<div className="grid sm:grid-cols-2 gap-2 max-h-[420px] overflow-y-auto pr-1">{available.map(row=><label key={row.id} className="flex items-center gap-3 rounded-xl border border-white/[.07] bg-white/[.018] px-3 py-3 cursor-pointer"><input type="checkbox" checked={selected.includes(row.serial_code)} onChange={()=>toggle(row.serial_code)}/><span className="font-mono text-xs text-white flex-1">{row.serial_code}</span><span className="text-[10px] text-text-dim">{formatCents(row.line_total_cents)}</span></label>)}</div>}</div>
    <div className="rounded-2xl border border-accent/20 p-5 sm:p-6 bg-accent/[.035]"><p className="text-[9px] uppercase tracking-[.18em] text-accent">AUTHORITATIVE CREDIT</p><h2 className="text-xl font-outfit font-semibold mt-1 mb-5">Emitir nota crédito</h2><Field label="Referencia" value={reference} onChange={setReference} placeholder="NC-0001"/><div className="mt-3"><label className="adminLabel">Motivo</label><select className="adminInput" value={reason} onChange={e=>setReason(e.target.value)}>{REASONS.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div><div className="mt-3"><label className="adminLabel">Punto receptor</label><select className="adminInput" value={returnLocation} onChange={e=>setReturnLocation(e.target.value)}>{locations.map(loc=><option key={loc.id} value={loc.code}>{loc.name} · {loc.location_type}</option>)}</select></div><div className="mt-3"><Field label="Notas" value={notesText} onChange={setNotesText} placeholder="Estado del producto / evidencia..."/></div><div className="rounded-xl border border-white/[.08] bg-black/20 p-4 mt-4"><Row label="Unidades" value={String(selected.length)}/><Row label="Crédito bruto" value={formatCents(grossCredit)}/><Row label="Reversión impuesto" value={formatCents(taxCredit)}/><p className="text-[10px] text-text-dim mt-3 leading-relaxed">Los valores se derivan de los ítems originales. El impuesto se reparte por botella conservando exactamente los centavos reconocidos en la venta completa.</p></div>{!canManage&&<p className="text-xs text-amber-300 mt-4">Modo lectura: se requiere <span className="font-mono">sales.manage</span> para emitir una devolución.</p>}<Button onClick={()=>void submit()} disabled={!canManage||!selected.length||!returnLocation} loading={busy} variant="primary" size="sm" fullWidth className="mt-4">Registrar devolución de {selected.length} unidad(es)</Button></div></section>
    <section className="rounded-2xl border border-white/10 p-5 sm:p-6 bg-white/[.02]"><p className="text-[9px] uppercase tracking-[.18em] text-text-dim">CREDIT NOTE HISTORY</p><h2 className="text-xl font-outfit font-semibold mt-1 mb-4">Documentos de esta venta</h2>{saleNotes.length===0?<p className="text-sm text-text-muted">Sin notas crédito.</p>:<div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b border-white/[.07] text-text-dim"><th className="py-3 pr-4">Referencia</th><th className="py-3 pr-4">Motivo</th><th className="py-3 pr-4">Bruto</th><th className="py-3 pr-4">Impuesto</th><th className="py-3">Fecha</th></tr></thead><tbody>{saleNotes.map(note=><tr key={note.id} className="border-b border-white/[.045]"><td className="py-3 pr-4 font-mono text-white">{note.credit_reference||note.id.slice(0,8)}</td><td className="py-3 pr-4 text-text-muted">{note.reason_code}</td><td className="py-3 pr-4 text-white">{formatCents(note.gross_credit_cents)}</td><td className="py-3 pr-4 text-text-muted">{formatCents(note.tax_credit_cents)}</td><td className="py-3 text-text-muted">{new Date(note.confirmed_at).toLocaleString('es-CO')}</td></tr>)}</tbody></table></div>}</section></>}
    <style jsx global>{`.adminInput{width:100%;border-radius:12px;padding:11px 13px;background:rgba(255,255,255,.025);border:1px solid rgba(255,255,255,.09);color:#fff;outline:none}.adminLabel{display:block;font-size:9px;text-transform:uppercase;letter-spacing:.13em;color:var(--text-dim);margin-bottom:7px}`}</style>
  </div>;
}
function Metric({icon,label,value,accent=false}:{icon:React.ReactNode;label:string;value:string;accent?:boolean}){return <div className="rounded-2xl border p-4" style={{borderColor:accent?'rgba(201,169,98,.28)':'rgba(255,255,255,.08)',background:accent?'rgba(201,169,98,.05)':'rgba(255,255,255,.02)'}}><div className="text-accent mb-3">{React.cloneElement(icon as React.ReactElement<{size?:number}>,{size:15})}</div><p className="text-[9px] uppercase tracking-[.12em] text-text-dim">{label}</p><p className="text-base font-outfit font-semibold mt-2">{value}</p></div>}
function Field({label,value,onChange,placeholder}:{label:string;value:string;onChange:(value:string)=>void;placeholder?:string}){return <div><label className="adminLabel">{label}</label><input className="adminInput" value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div>}
function Row({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-4 py-2 border-b border-white/[.05]"><span className="text-[10px] text-text-dim">{label}</span><span className="text-[11px] text-white">{value}</span></div>}
