'use client';

import React from 'react';
import Link from 'next/link';
import {
  Activity, AlertTriangle, ArrowDown, ArrowUpRight, BarChart3, Bot, BrainCircuit,
  CheckCircle2, CircleDashed, Cpu, Database, Eye, FileText, Gauge, Layers3,
  Lock, Network, Search, ShieldCheck, UserCheck, Workflow, type LucideIcon,
} from 'lucide-react';
import { Container } from '@/components/ui';
import { Badge } from '@/components/ui/Badge';
import { FadeInSection } from '@/components/ui/FadeInSection';
import { useLanguage } from '@/contexts/LanguageContext';
import { TECHNOLOGY_PROOF, type ProofStatus } from '@/data/technology-proof';

type Status = ProofStatus;
type Capability = { icon: LucideIcon; title: string; description: string; status: Status; details: string[] };
type RiskLevel = { level: string; title: string; examples: string; rule: string };

const statusClass: Record<Status, string> = {
  LIVE: 'border-emerald-300/20 text-emerald-200 bg-emerald-300/[0.035]',
  PARTIAL: 'border-accent/20 text-accent bg-accent/[0.025]',
  'IN DEVELOPMENT': 'border-sky-300/20 text-sky-200/85 bg-sky-300/[0.025]',
  ROADMAP: 'border-white/[0.08] text-text-dim bg-white/[0.012]',
};
const statusDot: Record<Status, string> = { LIVE: 'bg-emerald-300', PARTIAL: 'bg-accent', 'IN DEVELOPMENT': 'bg-sky-300', ROADMAP: 'bg-white/35' };

function StatusPill({ status }: { status: Status }) {
  return <span className={`inline-flex items-center gap-2 rounded-full border px-3 py-1 text-[8px] font-medium uppercase tracking-[0.16em] ${statusClass[status]}`}><span className={`h-1.5 w-1.5 rounded-full ${statusDot[status]}`} aria-hidden="true" />{status}</span>;
}

function Pipeline({ steps }: { steps: { label: string; note?: string }[] }) {
  return <div className="grid gap-2" role="list" aria-label="AI architecture pipeline">{steps.map((step, index) => <React.Fragment key={step.label}><div role="listitem" className="grid grid-cols-[42px_1fr_auto] items-center gap-3 rounded-xl border border-white/[0.055] bg-black/20 px-4 py-3.5"><span className="font-mono text-[9px] text-accent/55">{String(index + 1).padStart(2, '0')}</span><div><p className="text-xs sm:text-sm text-white">{step.label}</p>{step.note && <p className="mt-1 text-[10px] leading-relaxed text-text-dim">{step.note}</p>}</div><Activity size={13} className="text-text-dim" aria-hidden="true" /></div>{index < steps.length - 1 && <ArrowDown size={12} className="mx-auto text-accent/35" aria-hidden="true" />}</React.Fragment>)}</div>;
}

function SectionHeader({ badge, title, text }: { badge: string; title: string; text: string }) {
  return <div className="mb-10 max-w-4xl sm:mb-14"><Badge variant="accent" className="mb-6">{badge}</Badge><h2 className="mb-5 font-outfit text-3xl font-semibold tracking-[-0.035em] text-white sm:text-4xl md:text-5xl">{title}</h2><p className="max-w-3xl text-sm leading-relaxed text-text-muted sm:text-base">{text}</p></div>;
}

function ArchitectureLayer({ title, status, items, icon: Icon }: { title: string; status: string; items: string[]; icon: LucideIcon }) {
  return <div className="rounded-2xl border border-white/[0.055] bg-white/[0.012] p-6 sm:p-7"><div className="mb-6 flex items-center justify-between gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full border border-accent/20 text-accent"><Icon size={17} /></div><span className="text-[8px] uppercase tracking-[0.16em] text-text-dim">{status}</span></div><h3 className="mb-5 font-outfit text-base text-white">{title}</h3><div className="flex flex-wrap gap-2">{items.map((item) => <span key={item} className="rounded-full border border-white/[0.055] px-2.5 py-1 text-[8px] uppercase tracking-[0.11em] text-text-dim">{item}</span>)}</div></div>;
}

export const AIPlatformSection: React.FC = () => {
  const { locale } = useLanguage();
  const es = locale === 'es';
  const aiProof = TECHNOLOGY_PROOF.find((item) => item.id === 'ai-layer');
  const overallStatus: Status = aiProof?.status ?? 'IN DEVELOPMENT';

  const copy = es ? {
    badge: 'CTG ONE AI · Arquitectura pública', eyebrow: 'Inteligencia integrada a la operación',
    title: 'La IA no es una función aislada.', highlight: 'Es una capa de inteligencia.',
    description: 'CTG One está construyendo una arquitectura para conectar datos autorizados, contexto, modelos, agentes y workflows dentro de su propio ecosistema. Esta página separa explícitamente lo que existe, lo que está en desarrollo y lo que permanece en roadmap.',
    current: 'Estado de plataforma', currentText: 'No existe todavía un runtime general de modelos, RAG o agentes promovido a producción. La arquitectura y la gobernanza están definidas; la capacidad permanece IN DEVELOPMENT.',
    evidence: 'Evidence before answers', evidenceText: 'Las respuestas factuales deben privilegiar contexto verificable, fuentes rastreables y controles antes que fluidez sin evidencia.',
    architectureBadge: '01 · AI Architecture', architectureTitle: 'Cómo entra la inteligencia al sistema.', architectureText: 'La autorización ocurre antes del modelo. La acción ocurre después de validación, políticas y, cuando corresponde, supervisión humana.',
    capabilitiesBadge: '02 · Capabilities', capabilitiesTitle: 'Capacidades con madurez explícita.', capabilitiesText: 'Un diagrama, una librería o un prompt no convierten una capacidad en LIVE. Cada bloque debe demostrar implementación, evaluación y operación.',
    agentBadge: '03 · Agent Runtime', agentTitle: 'Un agente es un sistema, no un chatbot.', agentText: 'El runtime objetivo combina modelo, contexto, herramientas, memoria controlada, permisos, políticas, evaluación y escalamiento humano.',
    knowledgeBadge: '04 · CTG Knowledge', knowledgeTitle: 'El primer candidato para IA verificable.', knowledgeText: 'CTG Knowledge se diseña como un sistema RAG con respuestas basadas en fuentes autorizadas. No se presenta como LIVE hasta que exista pipeline real, evaluación reproducible y evidencia operativa.',
    citationTitle: 'Citation-First AI', citationText: 'Pregunta → recuperación → ranking → contexto → generación → citas. Para conocimiento interno, una respuesta sin trazabilidad debe considerarse inferior a una respuesta sustentada.',
    humanBadge: '05 · Human Authority', humanTitle: 'La IA propone. Las personas autorizan.', humanText: 'La autonomía depende del riesgo. Las operaciones financieras, legales, de identidad y otras acciones sensibles conservan control humano explícito.',
    governanceBadge: '06 · Governance & Security', governanceTitle: 'Controlar la inteligencia antes de escalarla.', governanceText: 'Datos, permisos, tool scopes, prompt injection, privacidad, versionado, evaluación, fallbacks, costo y observabilidad forman parte del producto, no son anexos.',
    evaluationBadge: '07 · Evaluation', evaluationTitle: 'Una capacidad no está lista porque “parece funcionar”.', evaluationText: 'Antes de promover un sistema a LIVE debe existir un dataset de evaluación, métricas, revisión, comparación y criterios de release.',
    ecosystemBadge: '08 · Applied AI', ecosystemTitle: 'IA aplicada a problemas operativos concretos.', ecosystemText: 'Los casos se mantienen como desarrollo o roadmap mientras no exista evidencia técnica suficiente en cada unidad.',
    osBadge: '09 · CTG One OS', osTitle: 'La inteligencia se apoya en la plataforma compartida.', osText: 'CTG One OS aporta identidad, datos, seguridad, transacciones, documentos e integraciones. CTG One AI añade contexto, modelos, agentes y evaluación sobre límites autorizados.',
    proof: 'Ver estado técnico', labs: 'Explorar Labs', technology: 'Explorar Technology', products: 'Ver productos', demo: 'ARCHITECTURE DEMO · No ejecuta un modelo real',
  } : {
    badge: 'CTG ONE AI · Public architecture', eyebrow: 'Intelligence embedded into operations',
    title: 'AI is not an isolated feature.', highlight: 'It is an intelligence layer.',
    description: 'CTG One is building an architecture that connects authorized data, context, models, agents, and workflows across its own ecosystem. This page explicitly separates what exists, what is in development, and what remains on the roadmap.',
    current: 'Platform status', currentText: 'There is not yet a general production model runtime, RAG system, or agent runtime promoted to LIVE. Architecture and governance are defined; the capability remains IN DEVELOPMENT.',
    evidence: 'Evidence before answers', evidenceText: 'Factual answers should favor verifiable context, traceable sources, and controls over unsupported fluency.',
    architectureBadge: '01 · AI Architecture', architectureTitle: 'How intelligence enters the system.', architectureText: 'Authorization occurs before the model. Action occurs after validation, policy, and human oversight where required.',
    capabilitiesBadge: '02 · Capabilities', capabilitiesTitle: 'Capabilities with explicit maturity.', capabilitiesText: 'A diagram, library, or prompt does not make a capability LIVE. Every block must demonstrate implementation, evaluation, and operating evidence.',
    agentBadge: '03 · Agent Runtime', agentTitle: 'An agent is a system, not a chatbot.', agentText: 'The target runtime combines model, context, tools, controlled memory, permissions, policy, evaluation, and human escalation.',
    knowledgeBadge: '04 · CTG Knowledge', knowledgeTitle: 'The first candidate for verifiable AI.', knowledgeText: 'CTG Knowledge is designed as a RAG system producing source-grounded answers over authorized knowledge. It is not presented as LIVE until a real pipeline, reproducible evaluation, and operating evidence exist.',
    citationTitle: 'Citation-First AI', citationText: 'Question → retrieval → ranking → context → generation → citations. For internal knowledge, an untraceable answer should be considered inferior to a grounded answer.',
    humanBadge: '05 · Human Authority', humanTitle: 'AI proposes. Humans authorize.', humanText: 'Autonomy depends on risk. Financial, legal, identity, and other sensitive actions retain explicit human control.',
    governanceBadge: '06 · Governance & Security', governanceTitle: 'Control intelligence before scaling it.', governanceText: 'Data boundaries, permissions, tool scopes, prompt injection, privacy, versioning, evaluation, fallbacks, cost, and observability are part of the product, not add-ons.',
    evaluationBadge: '07 · Evaluation', evaluationTitle: 'A capability is not ready because it “seems to work”.', evaluationText: 'Before promoting a system to LIVE, an evaluation dataset, metrics, review process, comparison, and release criteria must exist.',
    ecosystemBadge: '08 · Applied AI', ecosystemTitle: 'AI applied to concrete operating problems.', ecosystemText: 'Use cases remain in development or roadmap until sufficient technical evidence exists for each business unit.',
    osBadge: '09 · CTG One OS', osTitle: 'Intelligence is built on the shared platform.', osText: 'CTG One OS provides identity, data, security, transactions, documents, and integrations. CTG One AI adds context, models, agents, and evaluation within authorized boundaries.',
    proof: 'View technology status', labs: 'Explore Labs', technology: 'Explore Technology', products: 'View products', demo: 'ARCHITECTURE DEMO · Does not execute a real model',
  };

  const mainPipeline = es ? [
    { label: 'Datos autorizados', note: 'Fuentes permitidas y delimitadas por identidad, rol y unidad.' }, { label: 'Ingesta', note: 'Documentos, eventos y sistemas internos pasan por validación.' }, { label: 'Contexto', note: 'Solo la información necesaria para la tarea.' }, { label: 'Retrieval', note: 'Recuperación semántica cuando el caso lo requiere.' }, { label: 'Modelo', note: 'Selección según política, tarea, costo y evaluación.' }, { label: 'Agente + herramientas', note: 'Herramientas explícitas, scope restringido y límites de acción.' }, { label: 'Workflow', note: 'Reglas determinísticas conectan inferencia con procesos.' }, { label: 'Supervisión humana', note: 'Obligatoria cuando el nivel de riesgo lo exige.' }, { label: 'Acción + auditoría', note: 'Resultado trazable con logs y evidencia suficiente.' },
  ] : [
    { label: 'Authorized data', note: 'Sources bounded by identity, role, and business unit.' }, { label: 'Ingestion', note: 'Documents, events, and internal systems pass through validation.' }, { label: 'Context', note: 'Only the information required for the task.' }, { label: 'Retrieval', note: 'Semantic retrieval where the use case requires it.' }, { label: 'Model', note: 'Selected according to policy, task, cost, and evaluation.' }, { label: 'Agent + tools', note: 'Explicit tools, restricted scope, and action limits.' }, { label: 'Workflow', note: 'Deterministic rules connect inference to processes.' }, { label: 'Human oversight', note: 'Required whenever the risk level demands it.' }, { label: 'Action + audit', note: 'Traceable outcome with logs and sufficient evidence.' },
  ];

  const capabilities: Capability[] = es ? [
    { icon: FileText, title: 'Document Intelligence', description: 'Extracción, clasificación, resumen y salidas estructuradas sobre documentos autorizados.', status: 'IN DEVELOPMENT', details: ['Parsing', 'Clasificación', 'Resumen', 'Structured output'] },
    { icon: Search, title: 'Knowledge Systems', description: 'Búsqueda semántica, RAG, recuperación contextual y respuestas con fuentes.', status: 'IN DEVELOPMENT', details: ['Semantic retrieval', 'RAG', 'Citations', 'Context boundaries'] },
    { icon: Bot, title: 'AI Agents', description: 'Agentes especializados con identidad, propósito, herramientas, permisos y escalamiento.', status: 'ROADMAP', details: ['Tool scopes', 'Policy', 'Human escalation', 'Audit'] },
    { icon: Workflow, title: 'AI Automation', description: 'Clasificación, routing, borradores, alertas y recomendaciones dentro de workflows controlados.', status: 'PARTIAL', details: ['Routing', 'Drafting', 'Alerts', 'Rules'] },
    { icon: BarChart3, title: 'Decision Support', description: 'Análisis y recomendaciones para apoyar decisiones, sin reemplazar autoridad humana en procesos sensibles.', status: 'ROADMAP', details: ['Analysis', 'Patterns', 'Scenarios', 'Recommendations'] },
    { icon: Gauge, title: 'AI Observability', description: 'Latencia, tokens, costo, errores, tool calls, escalamiento y calidad por caso de uso.', status: 'ROADMAP', details: ['Latency', 'Cost', 'Errors', 'Quality'] },
  ] : [
    { icon: FileText, title: 'Document Intelligence', description: 'Extraction, classification, summarization, and structured outputs over authorized documents.', status: 'IN DEVELOPMENT', details: ['Parsing', 'Classification', 'Summarization', 'Structured output'] },
    { icon: Search, title: 'Knowledge Systems', description: 'Semantic search, RAG, contextual retrieval, and source-grounded answers.', status: 'IN DEVELOPMENT', details: ['Semantic retrieval', 'RAG', 'Citations', 'Context boundaries'] },
    { icon: Bot, title: 'AI Agents', description: 'Specialized agents with identity, purpose, tools, permissions, and escalation.', status: 'ROADMAP', details: ['Tool scopes', 'Policy', 'Human escalation', 'Audit'] },
    { icon: Workflow, title: 'AI Automation', description: 'Classification, routing, drafting, alerts, and recommendations inside controlled workflows.', status: 'PARTIAL', details: ['Routing', 'Drafting', 'Alerts', 'Rules'] },
    { icon: BarChart3, title: 'Decision Support', description: 'Analysis and recommendations supporting decisions without replacing human authority in sensitive processes.', status: 'ROADMAP', details: ['Analysis', 'Patterns', 'Scenarios', 'Recommendations'] },
    { icon: Gauge, title: 'AI Observability', description: 'Latency, tokens, cost, failures, tool calls, escalation, and quality by use case.', status: 'ROADMAP', details: ['Latency', 'Cost', 'Errors', 'Quality'] },
  ];

  const agentFormula = es ? ['Modelo', 'Contexto', 'Herramientas', 'Memoria', 'Permisos', 'Política', 'Evaluación'] : ['Model', 'Context', 'Tools', 'Memory', 'Permissions', 'Policy', 'Evaluation'];
  const agents: [string, string, Status][] = es ? [
    ['CTG Knowledge Agent', 'Consulta documental con evidencia y dominio autorizado.', 'ROADMAP'], ['CTG Operations Agent', 'Análisis operacional transversal con herramientas restringidas.', 'ROADMAP'], ['CTG Customer Agent', 'Clasificación y asistencia de atención con escalamiento.', 'ROADMAP'], ['CTG Research Agent', 'Investigación, síntesis y organización de evidencia.', 'ROADMAP'], ['CTG Financial Analysis Agent', 'Análisis financiero sin ejecución autónoma de movimientos.', 'ROADMAP'],
  ] : [
    ['CTG Knowledge Agent', 'Document consultation with evidence and authorized domain boundaries.', 'ROADMAP'], ['CTG Operations Agent', 'Cross-operational analysis with restricted tools.', 'ROADMAP'], ['CTG Customer Agent', 'Customer-support classification and assistance with escalation.', 'ROADMAP'], ['CTG Research Agent', 'Research, synthesis, and evidence organization.', 'ROADMAP'], ['CTG Financial Analysis Agent', 'Financial analysis without autonomous movement execution.', 'ROADMAP'],
  ];
  const knowledgeFlow = es ? ['Documentos', 'Parsing', 'Chunking', 'Embeddings', 'Índice vectorial', 'Retrieval', 'LLM', 'Respuesta', 'Citas'] : ['Documents', 'Parsing', 'Chunking', 'Embeddings', 'Vector index', 'Retrieval', 'LLM', 'Answer', 'Citations'];
  const riskLevels: RiskLevel[] = es ? [
    { level: 'LOW', title: 'Bajo riesgo', examples: 'Resumen, clasificación, borradores.', rule: 'Puede automatizarse con validación y logging.' }, { level: 'MEDIUM', title: 'Riesgo medio', examples: 'Recomendaciones, respuestas a clientes, sugerencias operativas.', rule: 'Requiere límites, evaluación y escalamiento.' }, { level: 'HIGH', title: 'Alto riesgo', examples: 'Finanzas, legal, identidad, pagos, retiros, settlements.', rule: 'Autoridad humana explícita. Sin ejecución autónoma.' },
  ] : [
    { level: 'LOW', title: 'Low risk', examples: 'Summarization, classification, drafting.', rule: 'May be automated with validation and logging.' }, { level: 'MEDIUM', title: 'Medium risk', examples: 'Recommendations, customer responses, operational suggestions.', rule: 'Requires limits, evaluation, and escalation.' }, { level: 'HIGH', title: 'High risk', examples: 'Finance, legal, identity, payments, withdrawals, settlements.', rule: 'Explicit human authority. No autonomous execution.' },
  ];

  const governance: [LucideIcon, string, string][] = es ? [
    [ShieldCheck, 'Human-in-the-loop', 'Las decisiones sensibles exigen aprobación humana y una ruta clara de escalamiento.'], [Lock, 'Data boundaries', 'Identidad, rol, unidad y scope de datos se resuelven antes de la inferencia; nunca mediante el prompt únicamente.'], [AlertTriangle, 'Prompt injection', 'Entradas no confiables, tool allowlists, separación de políticas, validación de outputs y límites de herramientas.'], [Layers3, 'Versionado', 'Modelo, prompts, configuración y datasets de evaluación deben tener trazabilidad suficiente para reproducir cambios.'], [Gauge, 'Cost governance', 'Tokens, requests, latencia y costo por tarea/agente/unidad deben medirse antes de escalar.'], [Eye, 'Observabilidad', 'Request ID, modelo, tool calls, errores, escalamiento y resultado sin almacenar PII indiscriminadamente.'],
  ] : [
    [ShieldCheck, 'Human-in-the-loop', 'Sensitive decisions require human approval and a clear escalation path.'], [Lock, 'Data boundaries', 'Identity, role, business unit, and data scope are resolved before inference, never by prompt alone.'], [AlertTriangle, 'Prompt injection', 'Untrusted-input isolation, tool allowlists, policy separation, output validation, and tool limits.'], [Layers3, 'Versioning', 'Models, prompts, configuration, and evaluation datasets require enough traceability to reproduce changes.'], [Gauge, 'Cost governance', 'Tokens, requests, latency, and cost per task/agent/business unit should be measured before scale.'], [Eye, 'Observability', 'Request ID, model, tool calls, failures, escalation, and outcome without indiscriminate PII retention.'],
  ];

  const evaluation = es ? [
    ['Accuracy', 'Corrección de la tarea.'], ['Groundedness', 'Qué tan sustentada está la respuesta en el contexto disponible.'], ['Citation correctness', 'Correspondencia real entre afirmación y fuente.'], ['Retrieval quality', 'Calidad y relevancia del contexto recuperado.'], ['Safety', 'Respeto de límites, permisos y políticas.'], ['Latency', 'Tiempo de respuesta por caso de uso.'], ['Cost', 'Costo medido por tarea y volumen.'], ['Task completion', 'Capacidad de completar el objetivo sin acciones no autorizadas.'],
  ] : [
    ['Accuracy', 'Correctness for the target task.'], ['Groundedness', 'How strongly the answer is supported by available context.'], ['Citation correctness', 'Actual correspondence between claims and sources.'], ['Retrieval quality', 'Quality and relevance of retrieved context.'], ['Safety', 'Compliance with boundaries, permissions, and policy.'], ['Latency', 'Response time by use case.'], ['Cost', 'Measured cost per task and volume.'], ['Task completion', 'Ability to complete the objective without unauthorized actions.'],
  ];
  const appliedAI: [string, string, Status][] = es ? [
    ['PISÁO', 'Análisis de demanda, asistencia de marketing e inteligencia de inventario.', 'ROADMAP'], ['CTG Craft Beer', 'Análisis de producción, distribución y soporte analítico a la plataforma de inversión.', 'ROADMAP'], ['Bechara', 'Property matching, lead intelligence y análisis documental.', 'ROADMAP'], ['Education', 'Knowledge assistant, apoyo académico y learning analytics.', 'ROADMAP'], ['Legalyst', 'Document intelligence, investigación y organización de casos.', 'ROADMAP'],
  ] : [
    ['PISÁO', 'Demand analysis, marketing assistance, and inventory intelligence.', 'ROADMAP'], ['CTG Craft Beer', 'Production, distribution, and analytical support for the investment platform.', 'ROADMAP'], ['Bechara', 'Property matching, lead intelligence, and document analysis.', 'ROADMAP'], ['Education', 'Knowledge assistant, academic support, and learning analytics.', 'ROADMAP'], ['Legalyst', 'Document intelligence, research, and case organization.', 'ROADMAP'],
  ];

  return <section className="relative overflow-hidden bg-bg-primary">
    <div className="pointer-events-none absolute inset-0" aria-hidden="true"><div className="absolute -top-48 right-[-18%] h-[900px] w-[900px] rounded-full" style={{ background: 'radial-gradient(circle, rgba(212,162,89,0.08), transparent 68%)' }} /><div className="absolute inset-0 opacity-[0.13]" style={{ backgroundImage: 'linear-gradient(rgba(212,162,89,0.05) 1px, transparent 1px), linear-gradient(90deg, rgba(212,162,89,0.05) 1px, transparent 1px)', backgroundSize: '76px 76px' }} /></div>

    <div className="relative py-20 sm:py-28 md:py-36"><Container><FadeInSection><div className="grid gap-10 lg:grid-cols-[1.15fr_0.85fr] lg:items-end"><div><Badge variant="accent" className="mb-7">{copy.badge}</Badge><div className="mb-5 flex items-center gap-3"><span className="h-px w-8 bg-accent/60" /><span className="text-[9px] uppercase tracking-[0.24em] text-text-dim">{copy.eyebrow}</span></div><h1 className="mb-7 font-outfit text-4xl font-semibold leading-[1.01] tracking-[-0.045em] sm:text-5xl md:text-6xl xl:text-[4.8rem]"><span className="text-white">{copy.title}</span>{' '}<span className="text-accent">{copy.highlight}</span></h1><p className="max-w-3xl text-sm leading-relaxed text-text-muted sm:text-base">{copy.description}</p></div><div className="rounded-2xl border border-sky-300/15 bg-sky-300/[0.025] p-6 sm:p-8"><div className="mb-4 flex items-center justify-between gap-4"><BrainCircuit size={20} className="text-sky-200/80" /><StatusPill status={overallStatus} /></div><h2 className="mb-3 font-outfit text-xl text-white">{copy.current}</h2><p className="text-xs leading-relaxed text-text-muted sm:text-sm">{copy.currentText}</p></div></div></FadeInSection>
      <FadeInSection delay={0.08}><div className="mt-14 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-accent/15 bg-accent/[0.025] p-6 sm:p-8"><p className="mb-3 text-[9px] uppercase tracking-[0.2em] text-accent">CTG ONE TECHNOLOGY</p><h2 className="font-outfit text-2xl text-white">Evidence before claims.</h2></div><div className="rounded-2xl border border-white/[0.06] bg-white/[0.012] p-6 sm:p-8"><p className="mb-3 text-[9px] uppercase tracking-[0.2em] text-text-dim">CTG ONE AI</p><h2 className="font-outfit text-2xl text-white">{copy.evidence}.</h2><p className="mt-3 text-xs leading-relaxed text-text-muted">{copy.evidenceText}</p></div></div></FadeInSection></Container></div>

    <div className="relative border-y border-white/[0.035] bg-bg-secondary py-20 sm:py-28 md:py-32"><Container><FadeInSection><SectionHeader badge={copy.architectureBadge} title={copy.architectureTitle} text={copy.architectureText} /></FadeInSection><div className="grid gap-8 lg:grid-cols-[0.82fr_1.18fr] lg:gap-12"><FadeInSection direction="left"><div className="rounded-2xl border border-accent/15 bg-black/25 p-5 sm:p-7"><Pipeline steps={mainPipeline} /></div></FadeInSection><FadeInSection direction="right"><div className="grid h-full gap-4 sm:grid-cols-2">{([[Lock, 'Authorization first', es ? 'La autorización se resuelve antes de entregar contexto al modelo.' : 'Authorization is resolved before context reaches a model.'], [Network, es ? 'Contexto, no acceso total' : 'Context, not full access', es ? 'Cada tarea recibe un contexto mínimo y delimitado.' : 'Each task receives minimal, bounded context.'], [UserCheck, 'Human authority', es ? 'El nivel de riesgo determina el punto de aprobación humana.' : 'Risk level determines the human approval point.'], [Eye, 'Auditability', es ? 'Las acciones relevantes deben poder reconstruirse sin exponer secretos.' : 'Relevant actions should be reconstructable without exposing secrets.']] as [LucideIcon,string,string][]).map(([Icon,title,text]) => <div key={title} className="rounded-2xl border border-white/[0.055] bg-white/[0.012] p-6"><Icon size={18} className="mb-5 text-accent" /><h3 className="mb-2 font-outfit text-base text-white">{title}</h3><p className="text-xs leading-relaxed text-text-muted">{text}</p></div>)}</div></FadeInSection></div></Container></div>

    <div className="relative py-20 sm:py-28 md:py-32"><Container><FadeInSection><SectionHeader badge={copy.capabilitiesBadge} title={copy.capabilitiesTitle} text={copy.capabilitiesText} /></FadeInSection><div className="grid gap-px overflow-hidden rounded-2xl border border-white/[0.05] bg-white/[0.05] md:grid-cols-2 xl:grid-cols-3">{capabilities.map((item,index) => <FadeInSection key={item.title} delay={Math.min(index*0.04,0.16)}><div className="h-full bg-bg-primary p-6 sm:p-8"><div className="mb-7 flex items-start justify-between gap-4"><div className="flex h-11 w-11 items-center justify-center rounded-full border border-accent/20 text-accent"><item.icon size={18} /></div><StatusPill status={item.status} /></div><h3 className="mb-3 font-outfit text-lg text-white">{item.title}</h3><p className="mb-6 text-xs leading-relaxed text-text-muted">{item.description}</p><div className="flex flex-wrap gap-2">{item.details.map((detail) => <span key={detail} className="rounded-full border border-white/[0.055] px-2.5 py-1 text-[8px] uppercase tracking-[0.12em] text-text-dim">{detail}</span>)}</div></div></FadeInSection>)}</div></Container></div>

    <div className="relative border-y border-white/[0.035] bg-bg-secondary py-20 sm:py-28 md:py-32"><Container><FadeInSection><SectionHeader badge={copy.agentBadge} title={copy.agentTitle} text={copy.agentText} /></FadeInSection><div className="grid gap-8 lg:grid-cols-2 lg:gap-12"><FadeInSection direction="left"><div className="rounded-2xl border border-accent/15 bg-black/20 p-6 sm:p-8"><div className="mb-7 flex h-14 w-14 items-center justify-center rounded-full border border-accent/25 text-accent"><Bot size={23} /></div><div className="grid gap-2">{agentFormula.map((part,index) => <div key={part} className="flex items-center gap-3 rounded-lg border border-white/[0.05] bg-white/[0.01] px-4 py-3"><span className="font-mono text-[9px] text-accent/45">+</span><span className="text-xs text-white">{part}</span>{index===agentFormula.length-1 && <CheckCircle2 size={13} className="ml-auto text-accent" />}</div>)}</div></div></FadeInSection><FadeInSection direction="right"><div className="space-y-3">{agents.map(([title,description,status]) => <div key={title} className="rounded-xl border border-white/[0.055] bg-white/[0.012] p-5"><div className="mb-3 flex items-center justify-between gap-4"><h3 className="font-outfit text-sm text-white">{title}</h3><StatusPill status={status} /></div><p className="text-xs leading-relaxed text-text-muted">{description}</p></div>)}</div></FadeInSection></div></Container></div>

    <div className="relative py-20 sm:py-28 md:py-32"><Container><FadeInSection><SectionHeader badge={copy.knowledgeBadge} title={copy.knowledgeTitle} text={copy.knowledgeText} /></FadeInSection><div className="grid gap-8 lg:grid-cols-[1.15fr_0.85fr] lg:gap-12"><FadeInSection direction="left"><div className="rounded-2xl border border-white/[0.06] bg-white/[0.012] p-6 sm:p-8"><div className="mb-6 flex items-center justify-between"><div className="flex items-center gap-3"><Search size={18} className="text-accent" /><span className="text-[9px] uppercase tracking-[0.2em] text-text-dim">RAG ARCHITECTURE</span></div><StatusPill status="IN DEVELOPMENT" /></div><div className="grid gap-2 sm:grid-cols-3">{knowledgeFlow.map((step,index) => <div key={step} className="rounded-lg border border-white/[0.05] bg-black/15 p-3.5"><span className="mb-2 block font-mono text-[8px] text-accent/45">{String(index+1).padStart(2,'0')}</span><span className="text-[11px] text-white">{step}</span></div>)}</div></div></FadeInSection><FadeInSection direction="right"><div className="h-full rounded-2xl border border-accent/15 bg-accent/[0.025] p-6 sm:p-8"><FileText size={20} className="mb-6 text-accent" /><h3 className="mb-3 font-outfit text-xl text-white">{copy.citationTitle}</h3><p className="text-xs leading-relaxed text-text-muted sm:text-sm">{copy.citationText}</p><div className="mt-7 rounded-xl border border-white/[0.05] bg-black/20 p-4"><p className="mb-2 text-[8px] uppercase tracking-[0.18em] text-text-dim">{copy.demo}</p><p className="text-xs text-white">{es ? '¿Qué política respalda esta respuesta?' : 'Which policy supports this answer?'}</p><div className="mt-4 border-l border-accent/30 pl-4"><p className="text-[11px] leading-relaxed text-text-muted">{es ? 'Respuesta sustentada en contexto recuperado y acompañada por referencia a la fuente autorizada.' : 'Answer grounded in retrieved context and accompanied by a reference to the authorized source.'}</p><p className="mt-2 text-[9px] text-accent">SOURCE · document / section / version</p></div></div></div></FadeInSection></div></Container></div>

    <div className="relative border-y border-white/[0.035] bg-bg-secondary py-20 sm:py-28 md:py-32"><Container><FadeInSection><SectionHeader badge={copy.humanBadge} title={copy.humanTitle} text={copy.humanText} /></FadeInSection><div className="grid gap-4 md:grid-cols-3">{riskLevels.map((risk,index) => <FadeInSection key={risk.level} delay={index*0.05}><div className={`h-full rounded-2xl border p-6 sm:p-7 ${risk.level==='HIGH'?'border-red-300/15 bg-red-300/[0.02]':risk.level==='MEDIUM'?'border-accent/15 bg-accent/[0.02]':'border-white/[0.055] bg-white/[0.012]'}`}><p className="mb-4 font-mono text-[9px] tracking-[0.2em] text-text-dim">{risk.level}</p><h3 className="mb-3 font-outfit text-lg text-white">{risk.title}</h3><p className="mb-5 text-xs leading-relaxed text-text-muted">{risk.examples}</p><p className="border-t border-white/[0.05] pt-4 text-[11px] leading-relaxed text-accent">{risk.rule}</p></div></FadeInSection>)}</div><FadeInSection delay={0.12}><div className="mt-6 rounded-xl border border-red-300/15 bg-red-300/[0.018] p-5 text-xs leading-relaxed text-text-muted"><strong className="text-white">Financial safety:</strong> {es ? 'CTG One AI no puede aprobar retiros, ejecutar pagos, alterar el ledger, crear settlements, aprobar inversiones ni modificar balances de forma autónoma.' : 'CTG One AI cannot autonomously approve withdrawals, execute payments, alter the ledger, create settlements, approve investments, or modify balances.'}</div></FadeInSection></Container></div>

    <div className="relative py-20 sm:py-28 md:py-32"><Container><FadeInSection><SectionHeader badge={copy.governanceBadge} title={copy.governanceTitle} text={copy.governanceText} /></FadeInSection><div className="grid gap-px overflow-hidden rounded-2xl border border-white/[0.05] bg-white/[0.05] sm:grid-cols-2 lg:grid-cols-3">{governance.map(([Icon,title,text],index) => <FadeInSection key={title} delay={Math.min(index*0.04,0.16)}><div className="h-full bg-bg-primary p-6 sm:p-7"><Icon size={18} className="mb-5 text-accent" /><h3 className="mb-2 font-outfit text-base text-white">{title}</h3><p className="text-xs leading-relaxed text-text-muted">{text}</p></div></FadeInSection>)}</div></Container></div>

    <div className="relative border-y border-white/[0.035] bg-bg-secondary py-20 sm:py-28 md:py-32"><Container><FadeInSection><SectionHeader badge={copy.evaluationBadge} title={copy.evaluationTitle} text={copy.evaluationText} /></FadeInSection><div className="grid gap-8 lg:grid-cols-[0.8fr_1.2fr] lg:gap-12"><FadeInSection direction="left"><Pipeline steps={['Dataset','Run','Score','Review','Compare','Release'].map((label) => ({label}))} /></FadeInSection><FadeInSection direction="right"><div className="grid gap-3 sm:grid-cols-2">{evaluation.map(([title,text]) => <div key={title} className="rounded-xl border border-white/[0.055] bg-white/[0.012] p-5"><p className="mb-2 text-[10px] uppercase tracking-[0.13em] text-accent">{title}</p><p className="text-xs leading-relaxed text-text-muted">{text}</p></div>)}</div></FadeInSection></div></Container></div>

    <div className="relative py-20 sm:py-28 md:py-32"><Container><FadeInSection><SectionHeader badge={copy.ecosystemBadge} title={copy.ecosystemTitle} text={copy.ecosystemText} /></FadeInSection><div className="grid gap-3 lg:grid-cols-5">{appliedAI.map(([unit,description,status]) => <FadeInSection key={unit}><div className="h-full rounded-xl border border-white/[0.055] bg-white/[0.012] p-5"><div className="mb-5 flex items-start justify-between gap-3"><Cpu size={16} className="text-accent" /><StatusPill status={status} /></div><h3 className="mb-3 font-outfit text-sm text-white">{unit}</h3><p className="text-[11px] leading-relaxed text-text-muted">{description}</p></div></FadeInSection>)}</div></Container></div>

    <div className="relative border-y border-white/[0.035] bg-bg-secondary py-20 sm:py-28 md:py-32"><Container><FadeInSection><SectionHeader badge={copy.osBadge} title={copy.osTitle} text={copy.osText} /></FadeInSection><div className="grid gap-3 lg:grid-cols-3"><ArchitectureLayer title="CTG ONE OS" status="LIVE / PARTIAL" items={es ? ['Identidad','Datos','Seguridad','Transacciones','Documentos','Integraciones'] : ['Identity','Data','Security','Transactions','Documents','Integrations']} icon={Database} /><ArchitectureLayer title="CTG ONE AI" status="IN DEVELOPMENT" items={es ? ['Contexto','Modelos','Agentes','Evaluación','Governance','Observabilidad'] : ['Context','Models','Agents','Evaluation','Governance','Observability']} icon={BrainCircuit} /><ArchitectureLayer title={es ? 'UNIDADES OPERATIVAS' : 'OPERATING UNITS'} status="MIXED" items={['PISÁO','CTG Craft Beer','Bechara','Education','Legalyst','Guest Logistics']} icon={Network} /></div></Container></div>

    <div className="relative py-20 sm:py-28 md:py-32"><Container><FadeInSection><div className="rounded-3xl border border-accent/15 bg-accent/[0.025] p-7 sm:p-10 lg:p-12"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><div className="mb-5 flex items-center gap-3"><CircleDashed size={16} className="text-accent" /><span className="text-[9px] uppercase tracking-[0.2em] text-accent">AI PROOF LAYER</span></div><h2 className="max-w-3xl font-outfit text-3xl font-semibold tracking-[-0.035em] text-white sm:text-4xl">{es ? 'La evidencia, no el marketing, promueve una capacidad a LIVE.' : 'Evidence, not marketing, promotes a capability to LIVE.'}</h2></div><div className="flex flex-wrap gap-3 lg:justify-end"><Link href="/technology/status" className="inline-flex items-center gap-2 rounded-full border border-accent/25 px-4 py-2.5 text-[10px] uppercase tracking-[0.14em] text-accent transition hover:bg-accent/[0.06]">{copy.proof}<ArrowUpRight size={13} /></Link><Link href="/labs" className="inline-flex items-center gap-2 rounded-full border border-white/[0.08] px-4 py-2.5 text-[10px] uppercase tracking-[0.14em] text-text-muted transition hover:text-white">{copy.labs}<ArrowUpRight size={13} /></Link><Link href="/services" className="inline-flex items-center gap-2 rounded-full border border-white/[0.08] px-4 py-2.5 text-[10px] uppercase tracking-[0.14em] text-text-muted transition hover:text-white">{copy.technology}<ArrowUpRight size={13} /></Link><Link href="/products" className="inline-flex items-center gap-2 rounded-full border border-white/[0.08] px-4 py-2.5 text-[10px] uppercase tracking-[0.14em] text-text-muted transition hover:text-white">{copy.products}<ArrowUpRight size={13} /></Link></div></div></div></FadeInSection></Container></div>
  </section>;
};
