\set ON_ERROR_STOP on

select json_build_object(
  'snapshotAt', to_char(clock_timestamp() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
  'authUsers', (select count(*) from auth.users),
  'profiles', (select count(*) from public.profiles),
  'wallets', (select count(*) from public.wallets),
  'transactions', (select count(*) from public.transactions),
  'kycSubmissions', (select count(*) from public.kyc_submissions),
  'kycDocuments', (select count(*) from public.kyc_documents),
  'adminAuditEntries', (select count(*) from public.admin_audit_log),
  'storageObjectMetadata', (select count(*) from storage.objects),
  'investmentParticipantProfiles', (select count(*) from public.investment_participant_profiles),
  'investmentFormulaVersions', (select count(*) from public.investment_formula_versions),
  'investmentBeerStyles', (select count(*) from public.investment_beer_styles),
  'investmentLots', (select count(*) from public.investment_production_lots),
  'investmentOrders', (select count(*) from public.investment_orders),
  'investmentFundingAllocations', (select count(*) from public.investment_funding_allocations),
  'investmentPaymentReceipts', (select count(*) from public.investment_payment_receipts),
  'investmentLedgerEntries', (select count(*) from public.investment_ledger_entries),
  'investmentSettlements', (select count(*) from public.investment_settlements),
  'investmentSales', (select count(*) from public.investment_sales),
  'investmentBottleUnits', (select count(*) from public.investment_bottle_units),
  'investmentWithdrawalRequests', (select count(*) from public.investment_withdrawal_requests),
  'investmentReinvestmentRequests', (select count(*) from public.investment_reinvestment_requests),
  'investmentPayouts', (select count(*) from public.investment_payouts),
  'investmentPayoutEvents', (select count(*) from public.investment_payout_events),
  'investmentAuditEntries', (select count(*) from public.investment_audit_log),
  'domainEvents', (select count(*) from public.system_domain_event_outbox),
  'notificationTemplates', (select count(*) from public.system_notification_templates),
  'notificationDeliveries', (select count(*) from public.system_notification_deliveries),
  'notificationDeliveryAttempts', (select count(*) from public.system_notification_delivery_attempts),
  'documentJobs', (select count(*) from public.system_document_jobs),
  'migrationCount', (select count(*) from supabase_migrations.schema_migrations),
  'latestMigration', (select max(version) from supabase_migrations.schema_migrations)
)::text;
