-- CTG One Wallet — Polygon chain submission + reconciliation V1
--
-- This migration advances an already authorized crypto_send intent through a
-- server-owned external lifecycle without granting signing/broadcast authority
-- to PostgreSQL or the browser.
--
-- Boundary:
--   * register_wallet_chain_submission_v1_server() records a client-observed tx
--     hash as a non-confirmed claim after durable authorization;
--   * record_wallet_chain_reconciliation_v1_server() accepts only evidence that
--     a trusted server adapter independently derived from Polygon;
--   * neither function signs, broadcasts, posts COP journal entries or mutates
--     balances;
--   * blockchain tx hashes remain globally idempotent through both the intent
--     column and wallet_transaction_references_v2.

alter table public.wallet_intents_v2
  add column if not exists submitted_at timestamptz,
  add column if not exists chain_last_checked_at timestamptz,
  add column if not exists chain_observed_at timestamptz,
  add column if not exists chain_confirmed_at timestamptz,
  add column if not exists chain_block_number bigint,
  add column if not exists chain_confirmations bigint,
  add column if not exists chain_reconciliation_digest_sha256 text,
  add column if not exists chain_failure_code text;

alter table public.wallet_intents_v2
  add constraint wallet_intents_v2_chain_block_number_check check (
    chain_block_number is null or chain_block_number > 0
  ),
  add constraint wallet_intents_v2_chain_confirmations_check check (
    chain_confirmations is null or chain_confirmations >= 0
  ),
  add constraint wallet_intents_v2_chain_reconciliation_digest_check check (
    chain_reconciliation_digest_sha256 is null
    or chain_reconciliation_digest_sha256 ~ '^[0-9a-f]{64}$'
  ),
  add constraint wallet_intents_v2_chain_failure_code_check check (
    chain_failure_code is null
    or chain_failure_code ~ '^WALLET_CHAIN_[A-Z0-9_]{3,96}$'
  ),
  add constraint wallet_intents_v2_submission_evidence_check check (
    submitted_at is null
    or (
      tx_hash is not null
      and status in ('submitted','pending_external','confirmed_external','reconciled','failed','replaced')
    )
  ),
  add constraint wallet_intents_v2_chain_confirmation_evidence_check check (
    chain_confirmed_at is null
    or (
      tx_hash is not null
      and chain_observed_at is not null
      and chain_block_number is not null
      and chain_confirmations is not null
    )
  );

create unique index if not exists wallet_intents_v2_chain_tx_hash_unique
  on public.wallet_intents_v2(lower(tx_hash))
  where tx_hash is not null;

create index if not exists wallet_intents_v2_chain_pending_idx
  on public.wallet_intents_v2(status, chain_last_checked_at, submitted_at)
  where status in ('submitted','pending_external','confirmed_external');

comment on column public.wallet_intents_v2.submitted_at is
  'First durable registration time for the claimed blockchain transaction hash. Registration is not confirmation.';
comment on column public.wallet_intents_v2.chain_reconciliation_digest_sha256 is
  'SHA-256 digest of canonical Polygon observation evidence generated by the trusted server reconciliation adapter.';
comment on column public.wallet_intents_v2.chain_failure_code is
  'Fail-closed chain reconciliation outcome. A failed intent never implies COP ledger mutation.';

create or replace function public.register_wallet_chain_submission_v1_server(
  p_user_id uuid,
  p_intent_id uuid,
  p_tx_hash text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_hash text := lower(trim(coalesce(p_tx_hash, '')));
  v_intent public.wallet_intents_v2;
  v_ref public.wallet_transaction_references_v2;
  v_rate_row public.api_rate_limit_windows;
  v_now timestamptz := clock_timestamp();
  v_replayed boolean := false;
begin
  if p_user_id is null or not exists (
    select 1 from public.profiles p where p.id = p_user_id
  ) then
    raise exception 'WALLET_CHAIN_CANONICAL_USER_INVALID';
  end if;
  if p_intent_id is null then
    raise exception 'WALLET_CHAIN_INTENT_ID_INVALID';
  end if;
  if v_hash !~ '^0x[0-9a-f]{64}$' then
    raise exception 'WALLET_CHAIN_TX_HASH_INVALID';
  end if;

  insert into public.api_rate_limit_windows(
    user_id, scope, window_started_at, request_count, updated_at
  ) values (
    p_user_id, 'wallet.intent-submit', v_now, 0, v_now
  ) on conflict (user_id, scope) do nothing;

  select * into v_rate_row
  from public.api_rate_limit_windows
  where user_id = p_user_id and scope = 'wallet.intent-submit'
  for update;

  if v_rate_row.window_started_at + interval '5 minutes' <= v_now then
    update public.api_rate_limit_windows
    set window_started_at = v_now, request_count = 1, updated_at = v_now
    where user_id = p_user_id and scope = 'wallet.intent-submit';
  elsif v_rate_row.request_count >= 20 then
    raise exception 'WALLET_CHAIN_SUBMIT_RATE_LIMITED';
  else
    update public.api_rate_limit_windows
    set request_count = request_count + 1, updated_at = v_now
    where user_id = p_user_id and scope = 'wallet.intent-submit';
  end if;

  select * into v_intent
  from public.wallet_intents_v2
  where id = p_intent_id
  for update;

  if v_intent.id is null or v_intent.user_id is distinct from p_user_id then
    raise exception 'WALLET_CHAIN_INTENT_NOT_FOUND';
  end if;
  if v_intent.intent_type is distinct from 'crypto_send'
     or v_intent.rail is distinct from 'polygon'
     or v_intent.chain_id is distinct from 137
     or v_intent.asset_symbol not in ('POL','CTG','USDC','USDT')
     or v_intent.amount_base_units is null
     or v_intent.destination_address is null then
    raise exception 'WALLET_CHAIN_INTENT_SHAPE_INVALID';
  end if;
  if v_intent.authorized_at is null
     or v_intent.authorized_wallet_address is null
     or v_intent.simulation_digest_sha256 is null then
    raise exception 'WALLET_CHAIN_AUTHORIZATION_EVIDENCE_MISSING';
  end if;

  if v_intent.status = 'authorized' then
    if v_intent.tx_hash is not null or v_intent.submitted_at is not null or v_intent.settled_at is not null then
      raise exception 'WALLET_CHAIN_EXTERNAL_STATE_CONFLICT';
    end if;
  elsif v_intent.status in ('submitted','pending_external','confirmed_external','reconciled','failed') then
    v_replayed := true;
    if lower(coalesce(v_intent.tx_hash, '')) is distinct from v_hash
       or v_intent.submitted_at is null then
      raise exception 'WALLET_CHAIN_SUBMISSION_REPLAY_CONFLICT';
    end if;
  else
    raise exception 'WALLET_CHAIN_SUBMISSION_STATUS_INVALID';
  end if;

  insert into public.wallet_transaction_references_v2(
    subject_user_id,
    intent_id,
    authority,
    reference_kind,
    reference_value
  ) values (
    p_user_id,
    v_intent.id,
    'blockchain',
    'tx_hash',
    v_hash
  )
  on conflict on constraint wallet_transaction_references_v2_authority_unique do nothing;

  select * into v_ref
  from public.wallet_transaction_references_v2 r
  where r.authority = 'blockchain'
    and r.reference_kind = 'tx_hash'
    and r.reference_normalized = v_hash
  limit 1;

  if v_ref.id is null then
    raise exception 'WALLET_CHAIN_REFERENCE_REGISTRATION_FAILED';
  end if;
  if v_ref.intent_id is distinct from v_intent.id
     or v_ref.subject_user_id is distinct from p_user_id then
    raise exception 'WALLET_CHAIN_TX_HASH_ALREADY_BOUND';
  end if;

  if not v_replayed then
    update public.wallet_intents_v2
    set status = 'submitted',
        tx_hash = v_hash,
        submitted_at = v_now,
        updated_at = v_now,
        metadata = metadata || jsonb_build_object(
          'chainSubmissionVersion', 'ctg-wallet-chain-submission-v1'
        )
    where id = v_intent.id
    returning * into v_intent;
  end if;

  return jsonb_build_object(
    'version', 'ctg-wallet-chain-submission-v1',
    'replayed', v_replayed,
    'intentId', v_intent.id,
    'status', v_intent.status,
    'txHash', v_intent.tx_hash,
    'submittedAt', v_intent.submitted_at
  );
end;
$$;

revoke all on function public.register_wallet_chain_submission_v1_server(uuid, uuid, text)
  from public, anon, authenticated;
grant execute on function public.register_wallet_chain_submission_v1_server(uuid, uuid, text)
  to service_role;

create or replace function public.record_wallet_chain_reconciliation_v1_server(
  p_user_id uuid,
  p_intent_id uuid,
  p_tx_hash text,
  p_observation_status text,
  p_evidence_digest_sha256 text,
  p_chain_observed boolean,
  p_block_number bigint,
  p_confirmations bigint,
  p_failure_code text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_hash text := lower(trim(coalesce(p_tx_hash, '')));
  v_status text := lower(trim(coalesce(p_observation_status, '')));
  v_digest text := lower(trim(coalesce(p_evidence_digest_sha256, '')));
  v_failure text := nullif(upper(trim(coalesce(p_failure_code, ''))), '');
  v_intent public.wallet_intents_v2;
  v_rate_row public.api_rate_limit_windows;
  v_now timestamptz := clock_timestamp();
  v_replayed boolean := false;
begin
  if p_user_id is null or not exists (
    select 1 from public.profiles p where p.id = p_user_id
  ) then
    raise exception 'WALLET_CHAIN_CANONICAL_USER_INVALID';
  end if;
  if p_intent_id is null then
    raise exception 'WALLET_CHAIN_INTENT_ID_INVALID';
  end if;
  if v_hash !~ '^0x[0-9a-f]{64}$' then
    raise exception 'WALLET_CHAIN_TX_HASH_INVALID';
  end if;
  if v_digest !~ '^[0-9a-f]{64}$' then
    raise exception 'WALLET_CHAIN_EVIDENCE_DIGEST_INVALID';
  end if;
  if v_status not in ('pending_external','confirmed_external','reconciled','failed') then
    raise exception 'WALLET_CHAIN_OBSERVATION_STATUS_INVALID';
  end if;
  if p_block_number is not null and p_block_number <= 0 then
    raise exception 'WALLET_CHAIN_BLOCK_NUMBER_INVALID';
  end if;
  if p_confirmations is not null and p_confirmations < 0 then
    raise exception 'WALLET_CHAIN_CONFIRMATIONS_INVALID';
  end if;

  if v_status in ('confirmed_external','reconciled') then
    if p_chain_observed is distinct from true
       or p_block_number is null
       or p_confirmations is null
       or p_confirmations < 1
       or v_failure is not null then
      raise exception 'WALLET_CHAIN_CONFIRMED_EVIDENCE_INVALID';
    end if;
  elsif v_status = 'failed' then
    if v_failure is null or v_failure !~ '^WALLET_CHAIN_[A-Z0-9_]{3,96}$' then
      raise exception 'WALLET_CHAIN_FAILURE_EVIDENCE_INVALID';
    end if;
  elsif v_failure is not null then
    raise exception 'WALLET_CHAIN_PENDING_FAILURE_CODE_INVALID';
  end if;

  insert into public.api_rate_limit_windows(
    user_id, scope, window_started_at, request_count, updated_at
  ) values (
    p_user_id, 'wallet.intent-reconcile', v_now, 0, v_now
  ) on conflict (user_id, scope) do nothing;

  select * into v_rate_row
  from public.api_rate_limit_windows
  where user_id = p_user_id and scope = 'wallet.intent-reconcile'
  for update;

  if v_rate_row.window_started_at + interval '5 minutes' <= v_now then
    update public.api_rate_limit_windows
    set window_started_at = v_now, request_count = 1, updated_at = v_now
    where user_id = p_user_id and scope = 'wallet.intent-reconcile';
  elsif v_rate_row.request_count >= 30 then
    raise exception 'WALLET_CHAIN_RECONCILE_RATE_LIMITED';
  else
    update public.api_rate_limit_windows
    set request_count = request_count + 1, updated_at = v_now
    where user_id = p_user_id and scope = 'wallet.intent-reconcile';
  end if;

  select * into v_intent
  from public.wallet_intents_v2
  where id = p_intent_id
  for update;

  if v_intent.id is null or v_intent.user_id is distinct from p_user_id then
    raise exception 'WALLET_CHAIN_INTENT_NOT_FOUND';
  end if;
  if v_intent.intent_type is distinct from 'crypto_send'
     or v_intent.rail is distinct from 'polygon'
     or v_intent.chain_id is distinct from 137
     or lower(coalesce(v_intent.tx_hash, '')) is distinct from v_hash
     or v_intent.submitted_at is null then
    raise exception 'WALLET_CHAIN_SUBMISSION_BINDING_INVALID';
  end if;

  if v_intent.status = 'reconciled' then
    if v_status <> 'reconciled' then
      raise exception 'WALLET_CHAIN_RECONCILED_TERMINAL';
    end if;
    v_replayed := true;
  elsif v_intent.status = 'failed' then
    if v_status <> 'failed' then
      raise exception 'WALLET_CHAIN_FAILED_TERMINAL';
    end if;
    v_replayed := true;
  elsif v_intent.status not in ('submitted','pending_external','confirmed_external') then
    raise exception 'WALLET_CHAIN_RECONCILIATION_STATUS_INVALID';
  end if;

  if not v_replayed then
    update public.wallet_intents_v2
    set status = v_status,
        chain_last_checked_at = v_now,
        chain_observed_at = case
          when p_chain_observed then coalesce(chain_observed_at, v_now)
          else chain_observed_at
        end,
        chain_confirmed_at = case
          when v_status in ('confirmed_external','reconciled') then coalesce(chain_confirmed_at, v_now)
          else chain_confirmed_at
        end,
        chain_block_number = p_block_number,
        chain_confirmations = p_confirmations,
        chain_reconciliation_digest_sha256 = v_digest,
        chain_failure_code = v_failure,
        settled_at = case
          when v_status = 'reconciled' then coalesce(settled_at, v_now)
          else settled_at
        end,
        updated_at = v_now,
        metadata = metadata || jsonb_build_object(
          'chainReconciliationVersion', 'ctg-wallet-chain-reconciliation-v1'
        )
    where id = v_intent.id
    returning * into v_intent;
  end if;

  return jsonb_build_object(
    'version', 'ctg-wallet-chain-reconciliation-v1',
    'replayed', v_replayed,
    'intentId', v_intent.id,
    'status', v_intent.status,
    'txHash', v_intent.tx_hash,
    'submittedAt', v_intent.submitted_at,
    'chainLastCheckedAt', v_intent.chain_last_checked_at,
    'chainObservedAt', v_intent.chain_observed_at,
    'chainConfirmedAt', v_intent.chain_confirmed_at,
    'chainBlockNumber', v_intent.chain_block_number,
    'chainConfirmations', v_intent.chain_confirmations,
    'chainFailureCode', v_intent.chain_failure_code,
    'settledAt', v_intent.settled_at
  );
end;
$$;

revoke all on function public.record_wallet_chain_reconciliation_v1_server(uuid, uuid, text, text, text, boolean, bigint, bigint, text)
  from public, anon, authenticated;
grant execute on function public.record_wallet_chain_reconciliation_v1_server(uuid, uuid, text, text, text, boolean, bigint, bigint, text)
  to service_role;

-- Keep direct authoritative mutation blocked. Only the two reviewed server RPCs
-- above may advance the chain lifecycle.
revoke insert, update, delete on public.wallet_intents_v2
  from public, anon, authenticated, service_role;
revoke insert, update, delete on public.wallet_transaction_references_v2
  from public, anon, authenticated, service_role;
